### ISSUE TITLE
Converting Gregorian date to Jalali date has error

### ISSUE THREAD

**Issue by marjandejyab** [nainemom/idate#9]
It seems there is a bug in the package. When we convert a date, the converted Month is one less than expected.
You can see it in the following picture. It should be [1399, 7, 30] (equal to 2020 oct 21)

<img width="353" alt="Screen Shot 2020-10-21 at 1 47 53 PM" src="https://user-images.githubusercontent.com/25340570/96707970-7053be00-13a5-11eb-8506-6bf98c782038.png">

**Comment by nainemom** [comment]
I guess you are doing it wrong. the `jdate` and `gdate` objects inside `IDate` instance are internal objects and you have to use **only** date methods like `getMonth` and `getFullYear` and etc.

also the `getMonth` and second item in `jdate` array is month index, not month number. so index 6 is equal to seventh month of persian year (Mehr).
